 from flask import Flask
app = Flask(__name__)
ECO="0776051066"
WA="263776051066"
@app.route("/")
def home():
 return f"""<html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{{margin:0;font-family:Arial;background:#e8f5e9}} .top{{background:#009739;color:#fff;text-align:center;padding:30px 10px;font-size:28px;font-weight:bold}} .wrap{{padding:0; margin:0; width:100%}} .card{{background:#fff;margin:15px;padding:25px;border-radius:15px}} input{{width:100%;padding:18px;font-size:22px;border:2px solid #009739;border-radius:10px;margin:10px 0}} button{{width:100%;padding:18px;background:#009739;color:#fff;border:none;border-radius:12px;font-size:20px;font-weight:bold}} #p{{font-size:36px;text-align:center;color:#009739;font-weight:bold;margin:15px 0}} .bigbtn{{display:block;padding:20px;border-radius:12px;text-align:center;text-decoration:none;font-weight:bold;font-size:19px;margin:15px}}</style></head><body><div class='top'>🇿🇼 Tuckshop Bot<div style='background:gold;color:black;display:inline-block;padding:6px 18px;border-radius:20px;font-size:16px;margin-top:10px'>1 USD = 26.5 ZiG</div></div><div class='wrap'><div class='card'><h2 style='color:#009739;margin:0 0 10px'>Profit Calculator</h2>Cost $<input id='c' type='number' value='10'>Sell $<input id='s' type='number' value='15'><button onclick="document.getElementById('p').innerHTML='Profit $'+(s.value-c.value)">CALCULATE PROFIT</button><div id='p'>Profit $5</div></div><a class='bigbtn' style='background:#25D366;color:white' href='https://wa.me/{WA}?text=ADD me to group'>✅ JOIN FREE WHATSAPP GROUP<br><small>Harare Cheap Stock - 0776051066</small></a><div class='card'><h3>💰 Make More Money</h3><a class='bigbtn' style='background:#eee;color:black' href='/suppliers'>🔍 Find Cheap Suppliers (Save 20%)</a><a class='bigbtn' style='background:gold;color:black' href='/premium'>Unlock Premium - $5/month</a></div><div class='card' style='background:gold;border:3px solid black;text-align:center'><h2 style='margin:0'>📢 WHOLESALER? ADVERTISE $10!</h2><p>Get 100+ tuckshop owners daily!</p><a class='bigbtn' style='background:#009739;color:white' href='https://wa.me/{WA}?text=I want to advertise $10'>ADVERTISE NOW - $10<br>EcoCash {ECO}</a></div><p style='text-align:center;color:gray;padding:20px'>Made in Harare ❤️<br>WhatsApp: 0776051066<br>EcoCash USD {ECO}</p></div></body></html>"""
@app.route("/suppliers")
def s(): return "<h1>Suppliers page - coming soon</h1><a href='/'>Back</a>"
@app.route("/premium")
def p(): return f"<h1>Premium $5 - EcoCash {ECO}</h1><a href='/'>Back</a>"
if __name__=="__main__": app.run()
