from flask import Flask
app=Flask(__name__)
@app.route("/")
def home():
 return """<html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{margin:0;font-family:Arial;background:#e8f5e9}.top{background:#009739;color:#fff;text-align:center;padding:25px 10px;font-size:26px;font-weight:bold}.card{background:#fff;margin:12px;padding:20px;border-radius:15px}input{width:100%;padding:16px;font-size:20px;border:2px solid #009739;border-radius:10px;margin:8px 0;box-sizing:border-box}button{width:100%;padding:16px;background:#009739;color:#fff;border:none;border-radius:12px;font-size:18px;font-weight:bold}.profit{font-size:32px;text-align:center;color:#009739;font-weight:bold;margin:12px 0}.btn{display:block;padding:16px;border-radius:12px;text-align:center;text-decoration:none;font-weight:bold;font-size:17px;margin:12px}.zig{background:#fff8e1;border:2px solid gold}</style><script>function calc(){let c=parseFloat(document.getElementById('c').value)||0;let s=parseFloat(document.getElementById('s').value)||0;let p=s-c;let perc=c>0?((p/c)*100).toFixed(1):0;document.getElementById('p').innerHTML='Profit $'+p+' ('+perc+'%)';document.getElementById('zig').innerHTML='ZiG Profit: '+(p*26.5).toFixed(2)+' ZiG<br>Sell: '+(s*26.5).toFixed(2)+' ZiG';}function usdToZig(){let u=document.getElementById('u').value||0;document.getElementById('zout').innerHTML=(u*26.5).toFixed(2)+' ZiG';}</script></head><body><div class='top'>Tuckshop Bot PRO<br><span style='background:gold;color:black;padding:5px 15px;border-radius:20px;font-size:14px'>1 USD = 26.5 ZiG - TODAY</span></div><div class='card'><h2 style='color:#009739;margin:0'>Profit Calculator</h2>Cost $<input id='c' type='number' value='10' oninput='calc()'>Sell $<input id='s' type='number' value='15' oninput='calc()'><button onclick='calc()'>CALCULATE PROFIT</button><div id='p' class='profit'>Profit $5 (50%)</div><div id='zig' style='text-align:center;background:gold;padding:10px;border-radius:10px;font-weight:bold'>ZiG Profit: 132.5 ZiG<br>Sell: 397.5 ZiG</div></div><div class='card zig'><h3 style='margin:0'>USD to ZiG Converter</h3>USD $<input id='u' type='number' value='1' oninput='usdToZig()'><button onclick='usdToZig()' style='background:gold;color:black'>CONVERT TO ZiG</button><div id='zout' class='profit' style='font-size:28px'>26.5 ZiG</div></div><a class='btn' style='background:#25D366;color:white' href='https://wa.me/263776051066?text=ADD me'>JOIN FREE WHATSAPP GROUP<br>Daily Cheap Stock - 0776051066</a><div class='card' style='background:gold;border:3px solid black;text-align:center'><h2 style='margin:0'>WHOLESALER? ADVERTISE $10!</h2><p>100+ owners see you DAILY!</p><a class='btn' style='background:#009739;color:white' href='https://wa.me/263776051066?text=I want to ADVERTISE $10'>ADVERTISE NOW<br>EcoCash 0776051066</a></div><p style='text-align:center;color:gray;padding:15px'>Made in Harare 0776051066</p></body></html>"""
@app.route("/suppliers")
def s(): return "<h1>Suppliers Coming</h1><a href='/'>Back</a>"
@app.route("/premium")
def p(): return "<h1>Premium $5 EcoCash 0776051066</h1><a href='/'>Back</a>"
if __name__=="__main__": app.run()
